version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "monthly"
    target-branch: "dev"
    reviewers:
      - "OleksandrPozden"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    reviewers:
      - "yura0611"
