# Generated by Django 4.2 on 2023-04-22 12:37
import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_orderproduct_order_goods"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(validators=[orders.models.PhoneNumberValidator()]),
                ),
                ("city", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=512)),
                ("building", models.CharField(max_length=4)),
                ("flat_number", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
