# Generated by Django 4.1.7 on 2023-02-25 19:57
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productinventory_remove_product_amount"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productinventory",
            table="products_product_inventory",
        ),
    ]
