# Generated by Django 4.1.7 on 2023-03-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productinventory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['-updated_at']},
        ),
    ]
