# Generated by Django 4.1.7 on 2023-03-08 19:36
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0001_initial"),
        ("products", "0005_alter_product_options_alter_productinventory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                related_name="products", to="pictures.picture"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pictures.picture",
            ),
        ),
    ]
