# Generated by Django 4.1.7 on 2023-03-21 22:37
import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="products",
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
