# Generated by Django 4.1.7 on 2023-03-22 16:06
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_remove_review_products_review_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
