# Generated by Django 4.1.7 on 2023-03-23 15:51
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_review_published_at_alter_review_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
    ]
