# Generated by Django 4.1.7 on 2023-03-24 16:19
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0001_initial"),
        ("products", "0010_alter_review_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pictures.picture",
            ),
        ),
    ]
