# Generated by Django 4.1.7 on 2023-03-24 16:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0001_initial"),
        ("products", "0011_alter_product_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                db_constraint=False, related_name="products", to="pictures.picture"
            ),
        ),
    ]
