# Generated by Django 4.1.7 on 2023-03-24 16:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0001_initial"),
        ("products", "0012_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pictures.picture",
            ),
        ),
    ]
