# Generated by Django 4.1.7 on 2023-03-24 17:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pictures", "0002_alter_picture_title"),
        ("products", "0013_alter_product_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                db_constraint=False,
                related_name="products",
                to="pictures.picture",
            ),
        ),
    ]
