# Generated by Django 4.1.7 on 2023-03-23 11:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="vengefulIcecream629", max_length=150, unique=True
            ),
        ),
    ]
