# Generated by Django 4.1.7 on 2023-03-26 09:27
import functools

import random_username.generate
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=functools.partial(
                    random_username.generate.UsernameGenerator.generate_username,
                    *(),
                    **{"num_digits": 3}
                ),
                max_length=150,
                unique=True,
            ),
        ),
    ]
