# Generated by Django 4.2 on 2023-04-14 19:46
import user.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_managers_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
