# Generated by Django 4.1.7 on 2023-03-24 16:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="dreadfulPretzels955", max_length=150, unique=True
            ),
        ),
    ]
