# Generated by Django 4.1.7 on 2023-03-24 17:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="empathicOryx418", max_length=150, unique=True
            ),
        ),
    ]
